import type { FastifyReply, FastifyRequest, HookHandlerDoneFunction } from 'fastify';
import { requestContext } from '../request-context';

/**
 * Fastify `onRequest` hook that establishes request correlation.
 *
 * The id itself is generated by the adapter's `genReqId` (honouring a valid
 * inbound `x-request-id`, else a fresh UUIDv7), so `request.id` is already the
 * canonical value here. This hook simply (1) mirrors it onto `request.requestId`
 * for direct reads, (2) echoes it back in the response header, and (3) runs the
 * remainder of the request inside AsyncLocalStorage so every log line, the
 * envelope, and audit rows share the same id.
 */
export function createRequestIdHook(headerName: string) {
  const header = headerName.toLowerCase();
  return function requestIdHook(
    request: FastifyRequest,
    reply: FastifyReply,
    done: HookHandlerDoneFunction,
  ): void {
    const requestId = String(request.id);
    request.requestId = requestId;
    void reply.header(header, requestId);
    requestContext.run({ requestId }, done);
  };
}
